---
- name: Install dependencies
  apt:
    name:
      - docker.io
      - docker-compose
    state: present
    update_cache: yes

- name: Create data directory
  file:
    path: "{{ uptime_kuma_data_dir }}"
    state: directory
    mode: '0755'

- name: Run Uptime Kuma container
  community.docker.docker_container:
    name: uptime-kuma
    image: louislam/uptime-kuma:1
    state: started
    restart_policy: always
    ports:
      - "{{ uptime_kuma_port }}:3001"
    volumes:
      - "{{ uptime_kuma_data_dir }}:/app/data"
